name: diabetes_buddy
description: A gamified diabetes education app using Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version information
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_analytics: ^10.3.0
  firebase_messaging: ^14.5.0

  # State management
  provider: ^6.0.5

  # UI packages
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^14.0.0+1
  youtube_player_flutter: ^8.1.2
  share_plus: ^7.0.0
  path_provider: ^2.0.15
  pdf: ^3.10.1
  printing: ^5.10.3
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl: ^0.18.0

  # Offline support and connectivity
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utility packages
  http: ^0.13.6
  url_launcher: ^6.1.11
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500